### ISSUE TITLE
What should happen when applying opacity less than 1 to a node with descendants?

### ISSUE THREAD

**Issue by trusktr** [keithclark/surrogate#1]
Hello Keith,

I'd like your opinion (since you have experience with 3D as seen in your FPS demo):

If we have a node in a 3D scene graph, and it has many descendants (a sub tree), what should happen when we apply opacity with a value less than `1` to it?
1. It, and all of it's children should become transparent, multiplying opacities down the scene graph.
2. It's content should become transparent but not that of its descendants.
3. Same as (1), but the whole object should be flattened into a plane.

The reason I want your opinion is because the new specs for CSS 3D (css-transforms) [state here](https://drafts.csswg.org/css-transforms/#grouping-property-values) that the answer is (3).

To see what I mean, view these two examples in Chrome 53 or higher:
- https://jsfiddle.net/trusktr/ymonmo70/16
- https://jsfiddle.net/trusktr/ymonmo70/17

The second example has opacity applied to the node that contains all the sub-nodes which compose the car. The opacity, according to spec, flattens the car into a plane (turns it into paper!).

I'm asking various 3D engine authors for opinions of what the correct or most expected behavior should be.

All the best,
~ Joe

**Comment by keithclark** [comment]
Closing this as it's completely unrelated to this repo. Feel free to contact me via [twitter](https://twitter.com/keithclarkcouk) or my [website](http://keithclark.co.uk/) if you want to discuss this.

**Comment by trusktr** [comment]
Hi Keith,

I'd simply just like to get a public opinion on the topic (and it's hard to do that within 140 characters). Emailing you directly also isn't very public. You also don't appear to have the FPS demo on github! Maybe you can put it on github and I can open an issue there?

Your public opinion on the subject would be highly appreciated. :]

- Joe

**Comment by trusktr** [comment]
Thanks for your [public opinion](https://twitter.com/keithclarkcouk/status/781608471401725956) on twitter! :D

For reference, in case people don't look at the replies on Twitter, someone replied and posted a perfect article with examples of the tricky behavior: https://css-tricks.com/things-watch-working-css-3d/

**Comment by trusktr** [comment]
(Last message) For reference, in case people don't look at the replies on Twitter, someone replied and posted a perfect article with examples of the tricky behavior: https://css-tricks.com/things-watch-working-css-3d/
